import { Activity } from '../entities/activity.entity';

export type RecommendationReason =
  | 'NEXT_IN_SEQUENCE'
  | 'POST_REMEDIATION'
  | 'POST_ACCELERATION'
  | 'MANDATORY_PRIORITY'
  | 'NO_ACTIVITY_AVAILABLE';

/**
 * Recommendation — BC3 aggregate
 * Represents the next suggested activity for a learner,
 * generated by the adaptive engine based on their path state.
 */
export class Recommendation {
  private constructor(
    public readonly learnerId: string,
    public readonly activity: Activity | null,
    public readonly reason: RecommendationReason,
    public readonly coverageAtRisk: boolean,
    public readonly generatedAt: Date,
  ) {}

  static forNextActivity(
    learnerId: string,
    activity: Activity,
    reason: RecommendationReason,
    coverageAtRisk: boolean,
  ): Recommendation {
    return new Recommendation(learnerId, activity, reason, coverageAtRisk, new Date());
  }

  static noActivityAvailable(learnerId: string): Recommendation {
    return new Recommendation(
      learnerId,
      null,
      'NO_ACTIVITY_AVAILABLE',
      false,
      new Date(),
    );
  }

  hasActivity(): boolean {
    return this.activity !== null;
  }
}
